---
- name: network backup playbook
  hosts: routers
  gather_facts: false

  vars:
    # cli_config only works with network_cli
    # *os_config specific modules can use multiple
    # connection types (e.g. httpapi, netconf, etc)
    ansible_connection: network_cli

  tasks:
    - name: remove non-config lines from Junos
      lineinfile:
        path: "backup/{{inventory_hostname}}.cfg"
        regexp: 'version '
        line: ''
      when: ansible_network_os == "junos"

    - name: perform agnostic restore
      cli_config:
        config: "{{ lookup('file', 'backup/{{inventory_hostname}}.cfg') }}"
