---
- name: network backup playbook
  hosts: routers
  gather_facts: false
  tasks:

    - name: perform agnostic backup
      cli_config:
        backup: yes
        backup_options:
          filename: "{{inventory_hostname}}.cfg"
          dir_path: ./
